### ISSUE TITLE
Simulator build issues after upgrading to flutter 2.5.x

### ISSUE THREAD

**Issue by chadrickman** [Tealium/tealium-flutter#14]
We recently upgraded our project to flutter 2.5.3 and are having issues building out to an iOS 15 simulator. We're getting the following error.

> /.pub-cache/hosted/pub.dartlang.org/tealium-2.0.1/ios/Classes/SwiftTealiumPlugin.swift:3:8: error: could not find module 'TealiumSwift' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64, at: /Users/crickman/code/hagerty-app/build/ios/Debug-iphonesimulator/tealium-swift/TealiumSwift.framework/Modules/TealiumSwift.swiftmodule

I'm curious if this [fix](https://github.com/Tealium/tealium-swift/commit/fb04b1b8c9ba1a07dea9152d810b5c65b4a61880) would resolve it?

**Comment by trister1997** [comment]
Hi @chadrickman! I tried replicating the issue and was not able to. I was also using Xcode 13 with Flutter 2.5.3, one thing I noticed is the issue is in your pub cache, could you try running `flutter clean` in your project directory, and also try running `dart pub cache clean` to clean up your pub cache and force a re-download of the dependency?

Also if possible could you put together a little demo app that has the issue and zip it up and attach it here?

Thanks!

**Comment by chadrickman** [comment]
@trister1997 @craigrouse - Thank you for your time! We have identified the issue and I'm going to leave this answer here for anyone else. This is not a Tealium issue, but back during the upgrade to XCode 12 there was a solution given by the Flutter community to fix support the transition was to exclude binaries built for the arm64 architecture. We still had this exclusion in place and it was removing the binary during the build only for simulators.

This [SO](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io) discusses in more detail the issue and why it was done back than. I apologize for the confusion, but hopefully this will help someone else in the future.

**Comment by craigrouse** [comment]
@chadrickman Thanks for letting us know! Glad you were able to solve it. On another note, we are currently preparing the update to upgrade the core libraries, and will post back on your other issue when that's ready.
