### ISSUE TITLE
Documentation for overrideLibrarySettingsURL / overrideTagManagementURL is confusing

### ISSUE THREAD

**Issue by fealXX** [Tealium/tealium-flutter#36]
Hi!

I hope this is the right place to raise this issue.

The documentation is a bit misleading, since the example for overrideLibrarySettingsURL states its for the mobile.html URL and the overrideTagManagementURL should contain the URL to the utag.js, while the correct setting for the overrideLibrarySettingsURL should be (as the name suggests, could've seen that one coming... :') ) the publish settings URL and the URL to the mobile.html for the overrideTagManagementURL. 

![image](https://github.com/Tealium/tealium-flutter/assets/7534146/00f2ad67-96c6-4047-a962-7e0eb557066f)

All the best,

Felix

**Comment by jameskeith** [comment]
Hi @fealXX  - thanks for letting us know.
I can confirm that the the `overrideTagManagementURL` should indeed be the URL to the relevant account/profile's `mobile.html` should it needs to be overridden.

The `overrideLibrarySettingsURL` can actually be the same URL. If you inspect the code of the `mobile.html` page then you'll see some settings in an `mps` object - these are the settings controlled and published from within the Tealium IQ mobile publish settings. So if this config option is pointing to a `mobile.html` page then we will extract those settings, otherwise it will need to point to a properly formatted settings file ( [example here](https://github.com/Tealium/tealium-kotlin/blob/main/mobile/src/main/assets/tealium-settings.json) )

What I can say, however, is that it shouldn't be pointing to `utag.js` - so I'll get this updated on our end.
In future, raising these queries here is fine, or just send it in a quick email to support@tealium.com

**Comment by fealXX** [comment]
Great, thank you! Thats a good hint, so we can just use the mobile.html URL in both fields from now on, right?

**Comment by craigrouse** [comment]
That's correct @fealXX! Apologies once again for the confusion.

**Comment by fealXX** [comment]
Thanks again! :)
